spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
      bindings:        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
          
server:  port: 8081
            