spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event
          
server:
  port: 8082
            